baseURL = "https://www.haiku-os.org/"
title = "Haiku Project"
copyright = "2001-2026 Haiku Inc."
locale = "en-us"

relativeURLs = true
buildDrafts = false
disableKinds = ["sitemap"]
pygmentsCodeFences = true
pygmentsStyle = "native"
theme = "shijin4"

[markup.goldmark.renderer]
# needed for inline HTML to be rendered
unsafe = true

[taxonomies]
  article = "articles"
  tag = "tags"
[params]
  AuthorName = "Haiku Project"
  discourseUrl = "https://discuss.haiku-os.org/"
  BuildTypeIsDeploy = false	  # Does not build sidebars & breadcrumbs when set to false

[security]
  # In Hugo >= 0.165 HTML files need to be whitelisted explicitly.
  # There is a lot of older ones existing alongside Markdown, so they are allowed.
  allowContent = ['^text/markdown$', '^text/html$']
